AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dungeon Master Go Backend (Serverless)

Globals:


  Function:
    Runtime: go1.x
    Architectures:
      - x86_64
    MemorySize: 256
    Timeout: 20

Resources:

  # -------------------------
  # API Gateway (REST API)
  # -------------------------
  DungeonMasterApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: DungeonMasterApi
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,client-id'"
        AllowMethods: "'POST,OPTIONS'"

  # -------------------------
  # Lambda Function (Go)
  # -------------------------
  DungeonMasterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dungeon-master-go
      CodeUri: cmd/lambda
      Handler: main
      Events:
        Chat:
          Type: Api
          Properties:
            RestApiId: !Ref DungeonMasterApi
            Path: /api/chat
            Method: POST

      Environment:
        Variables:
          CLOUDFLARE_ACCOUNT_ID: "{{resolve:ssm:/dm/cloudflare/account_id}}"
          CLOUDFLARE_API_TOKEN: "{{resolve:ssm:/dm/cloudflare/api_token}}"

      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dm/cloudflare/*

Outputs:

  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${DungeonMasterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/chat"
